# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/script_module.html
- name: Coping and executing scripts
  ansible.builtin.script: 
    cmd: "{{ item }} alex"
  with_items: "{{ scripts }}"
  register: result
  tags:
  - always

- debug:
    msg: "{{ item.stdout }}"
  with_items: "{{ result.results }}"
  tags:
  - never
  - debug