# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/command_module.html
- name: Execute a command in a dir
  ansible.builtin.command: 
    cmd: "{{ command }}"
    chdir: "{{ dir }}"
  register: result
  tags:
  - always

- debug:
    var: result.stdout
  tags:
  - never
  - debug