# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/command_module.html
- name: ls -la
  ansible.builtin.command: 
    cmd: ls -la "{{ file }}"
    chdir: "{{ dir }}"
  register: result
  tags:
  - always

- debug:
    var: result.stdout
  tags:
  - never
  - debug