version: "2.22"
services:
  ubuntu1:
    image: ubuntu:ssh
    container_name: ubuntu_ssh
    ports:
      - 2222:22
    secrets:
      - user_ssh_rsa
  ubuntu2:
    image: ubuntu:ssh
    container_name: ubuntu_ssh
    ports:
      - 3333:22
    secrets:
      - user_ssh_rsa
  ubuntu3:
    image: ubuntu:ssh
    container_name: ubuntu_ssh
    ports:
      - 4444:22
    secrets:
      - user_ssh_rsa

secrets:
  user_ssh_rsa:
    file: ~/.ssh/id_rsa_shared.pub