version: "2.22"
services:
  ubuntu1:
    image: ubuntu:ssh
    container_name: ubuntu_ssh1
    ports:
      - 1111:22
    secrets:
      - user_ssh_rsa
  ubuntu2:
    image: ubuntu:ssh
    container_name: ubuntu_ssh2
    ports:
      - 2222:22
    secrets:
      - user_ssh_rsa

secrets:
  user_ssh_rsa:
    file: ~/.ssh/id_rsa_shared.pub