# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/script_module.html
- name: Execute the script hello.sh in hosts
  hosts: ubuntu
  vars:
    script: ../hello.sh
  tasks:
  - name: Copy and execute {{ script }}
    ansible.builtin.script: 
      cmd: "{{ script }} alex"
    register: result
  - debug:
      var: result.stdout
