# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_module.html
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/yum_module.html
- name: Install NGINX in all hosts
  hosts: all
  tasks:
  - debug:
      var: ansible_os_family
  - name: Installing NGINX on Ubuntu or Debian
    ansible.builtin.apt:
      name: nginx
      state: present
    become: yes
    when: ansible_os_family == "Debian"
  - name: Install NGINX on Centos
    ansible.builtin.yum:
      name: nginx
      state: present
    when: ansible_os_family == "RedHat"